### ISSUE TITLE
loss_gp calculation in DRAGAN updater

### ISSUE THREAD

**Issue by BradMcDanel** [pfnet-research/chainer-gan-lib#4]
There appears to be an error in how the loss_gp term is computed. In the code snippet, `x_perturb` is used to calculate `y_mid`. However, `y_mid` is only used for the shape to create an array of ones, instead of the actual output from the discriminator. The values of `x_perturb` do not seem to be used to compute the `loss_gp`.

https://github.com/pfnet-research/chainer-gan-lib/blob/18b7c7dae445d5bee82010c4176ab173c6b97732/dragan/updater.py#L40-L43

**Comment by Aixile** [comment]
`self.dis(x_perturb)`  creates intermediate variables for backward calculation. They are stored in the model(https://github.com/pfnet-research/chainer-gan-lib/blob/master/common/net.py#L241) and are used in function `differentiable_backward`.

**Comment by BradMcDanel** [comment]
Thank you for the clarification. I missed that they were being stored internally. 

A follow-up question: What is the purpose of the `F.sigmoid` call in line 40? It seems like the result would not be used since it is not inside the model.

**Comment by Aixile** [comment]
`F.sigmoid` can be ignored here.

If you implement what the DRAGAN paper says, there would be an extra step, `differentiable_backward` through the `F.sigmoid` function, which used to calculate the gradient norm w.r.t "discriminator with sigmoid".
But doing this would cause a numerical problem, DRAGAN's author only calculates the gradient norm w.r.t "discriminator without sigmoid" in their implementation.

Ref https://github.com/kodalinaveen3/DRAGAN/issues/2

Note that the author said sigmoid can be ignored since it is monotonic, it might be a little confusing. Here is my understanding. 

In the paper, the author says 

> The space of linear functions, of course, forms a convex set and would therefore involve only a single global optimum.

What they want to do is to add constraints, so the region around the real-data manifold would be local convex. If the D without sigmoid is local linear(by their implementation), the result after the sigmoid is also local convex, which matches their original aim.

**Comment by BradMcDanel** [comment]
Thank you for your time and the detailed response!
